### ISSUE TITLE
Search is not working on 3.2.2 (627)

### ISSUE THREAD

**Issue by helfio** [slp/Telegram-FOSS#45] opened 2015-10-03 14:20 UTC
General nor inside chat. 

General search shows you the results but when you tap on them just open the proper chat, not shows you the message you looked for.
Inside chat search just doesn't show you any result.

**Comment by Bubu** [comment] 2015-10-05 07:49
Works for me after reinstalling Telegram. See #36 and #46. I didn't test it before, but I guess it is the same underlying Problem.

**Comment by geileszeuch** [comment] 2015-10-05 08:50
I can confirm this. Sadly, I cannot check if this a Telegram-Foss problem only or comes directly from upstream.

**Comment by helfio** [comment] 2015-10-10 08:07
Just as @Bubu I had it working with a fresh install. Lucky I had no secret chats

**Comment by Bubu** [comment] 2015-11-17 18:50
Does this work again in 3.2.6?

**Comment by geileszeuch** [comment] 2015-11-18 14:42
It still doesn't work in 3.2.6 for me.

**Comment by sevan6** [comment] 2015-11-21 07:06
For me it is fixed in 3.2.6
Installed from F-Droid

**Comment by Akronix** [comment] 2015-11-21 09:25
For me it is also working fine in 3.2.6 "fresh" installing (after uninstall upstream) from F-Droid.

**Comment by g11c** [comment] 2015-11-26 22:42
Installed from F-Driod and it doesn't work for me in 3.2.6

**Comment by Bubu** [comment] 2015-12-10 00:05
Can you check if this is fixed in 3.3.1? This should finally fix all connection.

**Comment by geileszeuch** [comment] 2015-12-10 17:20
Works perfectly again since 3.3.1 for me. Great job.

**Closed** 2015-12-11 00:09 UTC
