### ISSUE TITLE
URLs are not displayed as links in 3.2.2

### ISSUE THREAD

**Issue by haary** [slp/Telegram-FOSS#46] opened 2015-10-04 10:56 UTC
Since version 3.2.2 Telegram seems no longer recognize URL schemes. URLs are presented as normal text. The preview feature is also gone.

**Comment by Bubu** [comment] 2015-10-04 13:35
Yes, I can confirm. Bu the link preview gets generated just not displayed in the foss version.
Upstream Telegram works though.

**Comment by Allanitomwesh** [comment] 2015-10-05 06:15
Thought it was just me. Can confirm as well. Also affects hashtags (they aren't blue,so can't be clicked) and bot commands (the command happens but the command itself isn't blue)

**Comment by Bubu** [comment] 2015-10-05 07:40
This seems to be related to #36. After reinstalling Telegram again link previews and url handling works again.

**Comment by Allanitomwesh** [comment] 2015-10-05 08:27
Reinstalling huh? I'll give it a try

**Comment by geileszeuch** [comment] 2015-10-05 08:50
I have the same problem here since 3.2.2. Sadly, I cannot check if this a Telegram-Foss problem only or comes directly from upstream.

**Comment by Bubu** [comment] 2015-10-05 13:29
I found what went wrong. Emoji,replaceEmoji has the side effect of converting a CharSequence into a SpannableString.

**Comment by Allanitomwesh** [comment] 2015-10-07 05:23
Reinstalling didn't work for me.

**Comment by slp** [comment] 2015-10-10 07:53
@Bubu Good catch! PR merged.

**Comment by sevan6** [comment] 2015-10-23 14:21
Would this also fix the #hashtags that are not working anymore?

**Comment by Bubu** [comment] 2015-10-23 14:40
Yes, they use the same mechanism.

**Comment by Bubu** [comment] 2015-11-17 18:42
Fixed in new version

**Closed by Bubu** 2015-11-17 18:42 UTC

**Comment by beerisgood** [comment] 2015-11-21 01:21
3.2.6 from F-Droid have the same problems. (i upgrade from 3.1.3)
