### ISSUE TITLE
Unexpected closing/crash when tap-holding emojis

### ISSUE THREAD

**Issue by aphirst** [slp/Telegram-FOSS#56] opened 2015-12-01 20:53 UTC
I'm running 3.2.6 from F-Droid on CM11.0 presently (Android 4.4.4), and whenever I do a press-and-hold on seemingly any Emoji, I get the message (German locale settings) "Telegram wurde beendet", and Telegram closes promptly. Not sure what else to add, but I'll try to get a logcat once I have a bit of spare time *and* have access to my computer and phone at the same time.

**Comment by Bubu** [comment] 2015-12-01 22:19
This is already fixed in the new version.
There is still a bit of testing going on over in the other thread, I hope the new version will be available on fdroid within a week.

(Duplicate of #52)

**Closed by Bubu** 2015-12-01 22:19 UTC

**Comment by aphirst** [comment] 2015-12-02 04:02
Ah, apologies. I had neglected to check the **closed** bug report list for similar issues.

Looking forward to it. :smile:
