### ISSUE TITLE
Telegram crashes on Android share action

### ISSUE THREAD

**Issue by howey** [slp/Telegram-FOSS#115] opened 2016-08-26 03:08 UTC
In the tip, Telegram crashes when using an Android share action. For example:
1. Open the Android picture gallery, and open a picture
2. Click the three node graph icon to open the share action menu
3. Select Telegram
4. Telegram will crash

Below is a stack trace of the crash:

```
--------- beginning of crash
E/AndroidRuntime(30972): FATAL EXCEPTION: main
E/AndroidRuntime(30972): Process: org.telegram.messenger.beta, PID: 30972
E/AndroidRuntime(30972): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
E/AndroidRuntime(30972):    at java.util.regex.Matcher.reset(Matcher.java:177)
E/AndroidRuntime(30972):    at java.util.regex.Matcher.<init>(Matcher.java:90)
E/AndroidRuntime(30972):    at java.util.regex.Pattern.matcher(Pattern.java:297)
E/AndroidRuntime(30972):    at org.telegram.ui.LaunchActivity.handleIntent(LaunchActivity.java:646)
E/AndroidRuntime(30972):    at org.telegram.ui.LaunchActivity.onNewIntent(LaunchActivity.java:1366)
E/AndroidRuntime(30972):    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1239)
E/AndroidRuntime(30972):    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1255)
E/AndroidRuntime(30972):    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2503)
E/AndroidRuntime(30972):    at android.app.ActivityThread.performNewIntents(ActivityThread.java:2515)
E/AndroidRuntime(30972):    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2524)
E/AndroidRuntime(30972):    at android.app.ActivityThread.access$1700(ActivityThread.java:155)
E/AndroidRuntime(30972):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
E/AndroidRuntime(30972):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30972):    at android.os.Looper.loop(Looper.java:139)
E/AndroidRuntime(30972):    at android.app.ActivityThread.main(ActivityThread.java:5313)
E/AndroidRuntime(30972):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30972):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(30972):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/AndroidRuntime(30972):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

I have a patch! But I don't know the github workflow. I'm trying to figure that out right now. Otherwise I can email the patch to someone.

**Comment by vanitasvitae** [comment] 2016-09-10 19:49
Duplicate of #109

**Closed** 2016-11-04 08:35 UTC
