### ISSUE TITLE
Video compression doesn't work

### ISSUE THREAD

**Issue by Paviluf** [slp/Telegram-FOSS#85] opened 2016-03-14 00:30 UTC
I use the Telegram app from F-droid and when I try to capture a video to send it, it fail. If I disable the compression option it work but of course the video is much bigger. 

Is there anything particular needed to make the encoding work ? Note that I don't have anything from Google installed. I tried with an other phone that has Google services, Play store, etc... and the compression option works.

Thanks !

**Comment by Bubu** [comment] 2016-03-14 09:33
Compression and sending videos works on my Phone with CM12.1 and no google anything installed.

It should not depend on anything from google as it uses the ffmpeg libav library do encode the video. But the encoding is hardware dependent so it might be important to know what device you use.

You could also try and see if there are any outputs of [logcat](http://forum.xda-developers.com/showthread.php?t=1726238) that might show us what the problem is.

**Comment by Paviluf** [comment] 2016-03-14 11:21
I have a Motorola Razr i, it have an Intel x86 processor.
I will try to make a logcat.

**Comment by Paviluf** [comment] 2016-03-14 12:16
I made a [logcat](http://pastebin.com/Ez9cRSek), hope it help.

**Comment by jomo** [comment] 2016-03-14 12:22
This seems to be the important part:
```
03-14 13:09:38.951 I/OMXClient(2365): Using client-side OMX mux.
03-14 13:09:38.961 E/ACodec  (2365): [OMX.Intel.VideoEncoder.AVC] storeMetaDataInBuffers (output) failed w/ err -2147483648
03-14 13:09:38.961 I/ACodec  (2365): setupVideoEncoder succeeded
03-14 13:09:39.011 I/OMXClient(2365): Using client-side OMX mux.
03-14 13:09:39.011 E/ACodec  (2365): [OMX.Intel.VideoDecoder.AVC] storeMetaDataInBuffers failed w/ err -2147483648
03-14 13:09:39.011 I/ACodec  (2365): DRC Mode: Port Reconfig Mode
03-14 13:09:39.181 E/MediaMetadataRetrieverJNI(2365): getFrameAtTime: videoFrame is a NULL pointer
03-14 13:09:39.601 E/ACodec  (2365): [OMX.Intel.VideoEncoder.AVC] ERROR(0x80001001)
03-14 13:09:39.601 E/MediaCodec(2365): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
03-14 13:09:39.631 E/ACodec  (2365): [OMX.Intel.VideoEncoder.AVC] ERROR(0x80001001)
03-14 13:09:39.631 E/MediaCodec(2365): Codec reported an error. (omx error 0x80001001, internalError -2147483648)
```

**Comment by Paviluf** [comment] 2016-03-14 12:31
Note that I have a [CM11 ROM](http://forum.xda-developers.com/razr-i/development/rom-unofficial-cyanogenmod-11-t2966855). The problem can come from it too maybe ?

**Comment by Bubu** [comment] 2016-03-14 12:47
@jomo Thanks for looking at the log. It's hard to say where the actual problem is, there is a lot of video en/decoding going on.
I would point out this part:
```
03-14 13:09:39.801 I/FFmpegExtractor(154): android-source:0xb79b75f0
03-14 13:09:39.801 I/FFMPEG  (154): Last message repeated 1 times
03-14 13:09:39.801 I/FFMPEG  (154): [mov,mp4,m4a,3gp,3g2,mj2 @ 0xb7a4d280] moov atom not found
03-14 13:09:39.801 E/FFmpegExtractor(154): android-source:0xb79b75f0: avformat_open_input failed, err:Invalid data found when processing input
03-14 13:09:39.801 W/FFmpegExtractor(154): sniff through BetterSniffFFMPEG failed, try LegacySniffFFMPEG
03-14 13:09:39.801 E/FFmpegExtractor(154): android-source:0xb79b75f0|file:/storage/emulated/0/Android/data/org.telegram.messenger/cache/-2147483648_-210003.mp4: avformat_open_input failed, err:Invalid data found when processing input
03-14 13:09:39.801 D/FFmpegExtractor(154): SniffFFMPEG failed to sniff this source
```

But I'd have to look at the source how Telegram actually tries to encode the videos. Maybe we can reproduce this on a x86 Android emulator (Can you record video there?). But yes, it's still a possibility this is a bug in CM11 for that Motorola phone.

**Comment by Paviluf** [comment] 2016-03-14 13:08
I found that the encoding fail with the default audio format (AAC) but work with AMR-NB audio !

**Comment by Bubu** [comment] 2016-03-14 13:10
Where can you change the encoding format?

**Comment by Paviluf** [comment] 2016-03-14 13:14
There is a menu (the same as my default camera app) where I can choose some options at the right of the recording button.

**Comment by Paviluf** [comment] 2016-03-14 13:22
Is there something needed to handle AAC in Telegram ?

**Comment by Paviluf** [comment] 2016-03-14 15:04
Sorry I'm stupid, with AMR-NB audio the video is directly sent but uncompressed !
Telegram don't offer to compress the video with this audio format.

**Comment by Paviluf** [comment] 2016-03-15 12:32
Hazou, the creator of the CM 11 ROM for the Razr i, has maybe something to fix this problem in the ROM but he need time.

**Comment by DrKLO** [comment] 2016-03-16 22:00
@Bubu you wrong, Telegram uses Android MediaCodec API for decoding and encoding which broken by vendors almost on every android phone.

**Comment by Bubu** [comment] 2016-03-16 23:16
@DrKLO Thanks for the clarification. So this is not a Telegram(-FOSS) problem but a problem with your ROM. Hope you get it fixed, closing this.

**Closed by Bubu** 2016-03-16 23:16 UTC

**Comment by Paviluf** [comment] 2016-03-17 08:00
I hope too that Hazou can fix it in the ROM.
Thank you.
